[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
    bblanchon/ArduinoJson@^7.0.0
    links2004/WebSockets@^2.4.0
board_build.partitions = min_spiffs.csv
build_flags = 
    -DCORE_DEBUG_LEVEL=3
    -Ilib/SmartPlugSDK/src  
    -Isrc                  

lib_extra_dirs = 
    lib
    src